import { Resource } from '../types';

export const HRD_ARTICLES: Resource[] = [
  {
    id: 'flow-state-learning',
    type: 'blog',
    title: 'Flow State: สภาวะลื่นไหล กุญแจสำคัญสู่การเรียนรู้ระดับสูง (Deep Learning)',
    excerpt: 'ทำความรู้จัก Flow State และเทคนิคการออกแบบการเรียนรู้เพื่อเปลี่ยนบรรยากาศในองค์กรให้มีชีวิตชีวา',
    date: '2026-01-23',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
  {
    id: 'intro-to-facilitation',
    type: 'blog',
    title: 'ศิลปะการอำนวยความสะดวก (Facilitation Skills) สำหรับผู้นำยุคใหม่',
    excerpt: 'เจาะลึกบทบาทผู้นำในฐานะ Facilitator เพื่อสร้างการมีส่วนร่วมและผลลัพธ์ที่ยั่งยืน',
    date: '2026-01-22',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'training-management-guide',
    type: 'blog',
    title: 'Training Management 101: 4 ขั้นตอนปั้นแผนพัฒนาคนให้เห็นผลจริง (T1-T4 Cycle)',
    excerpt: 'คู่มือการวางแผนฝึกอบรมอย่างเป็นระบบด้วย T1-T4 Cycle เพื่อผลลัพธ์ที่วัดผลได้จริง',
    date: '2026-01-20',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80',
  },
  {
    id: 'ai-proof-skills-hr-2026',
    type: 'blog',
    title: 'ทักษะที่ AI แทนที่ไม่ได้ ในงานบริหารคนยุค 2026',
    excerpt: 'เมื่อ AI ก้าวเข้าสู่ยุค Agentic HR พรมแดนระหว่างงานเทคนิคและงานหัวใจก็ชัดเจนขึ้น มาดู 5 ทักษะที่ AI ไม่มีวันเลียนแบบได้ในการบริหารคนยุคใหม่',
    date: '2026-03-23',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80',
  },
  {
    id: 'hrd-future-skills-2025',
    type: 'blog',
    title: 'Future Skills 2025: ทักษะแห่งอนาคตที่ผู้นำองค์กรและ HRD ต้องรู้',
    excerpt: 'สำรวจทักษะสำคัญที่จำเป็นต่อการขับเคลื่อนองค์กรในโลกยุค BANI World พร้อมแนวทางการ Reskill และ Upskill พนักงานเพื่อให้พร้อมรับมือกับการเปลี่ยนแปลง',
    date: '2024-03-15',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80',
  },
  {
    id: 'building-growth-mindset-culture',
    type: 'blog',
    title: 'สร้างจิตสำนึกแห่งการเติบโต (Growth Mindset) ให้กลายเป็นวัฒนธรรมองค์กร',
    excerpt: 'Growth Mindset ไม่ใช่แค่ Buzzword แต่เป็นรากฐานสำคัญขององค์กรนวัตกรรม ครูเด่น มาสเตอร์ฟา เผยเคล็ดลับการปลูกฝัง Growth Mindset อย่างยั่งยืน',
    date: '2024-03-02',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'effective-leadership-communication',
    type: 'blog',
    title: 'ศิลปะการสื่อสารสำหรับผู้นำ: เปลี่ยนคำพูดให้เป็นพลังขับเคลื่อนทีม',
    excerpt: 'ปัญหาความขัดแย้ง 80% เกิดจากการสื่อสารที่ไม่ชัดเจน เรียนรู้เทคนิคการสื่อสารแบบ Empathic Communication เพื่อซื้อใจลูกน้องและลดปัญหาในทีม',
    date: '2024-02-18',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80',
  },
  {
    id: 'employee-engagement-strategies',
    type: 'blog',
    title: '5 กลยุทธ์รักษาคนเก่ง (Talent Retention) ด้วย Employee Engagement',
    excerpt: 'การขึ้นเงินเดือนอาจไม่ใช่คำตอบเดียวเสมอไป ค้นพบปัจจัยทางจิตวิทยาและกระบวนการจัดการที่ทำให้คนเก่งอยากอยู่กับองค์กรของคุณไปนานๆ',
    date: '2024-02-05',
    thumbnail: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&q=80',
  },
  {
    id: 'agile-hr-transformation',
    type: 'blog',
    title: 'Agile HR: ปรับโฉมงานทรัพยากรบุคคลให้รวดเร็วและตอบโจทย์ธุรกิจ',
    excerpt: 'เมื่อวงจรธุรกิจสั้นลง HR ต้องเร็วกว่าเดิม เรียนรู้วิธีการนำหลักการ Agile มาใช้ในกระบวนการประเมินผล การพัฒนาบุคลากร และสรรหาบุคลากร',
    date: '2024-01-20',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80',
  },
  {
    id: 'coaching-skills-for-managers',
    type: 'blog',
    title: 'จาก Manager สู่ Coach: ทักษะการโค้ชเพื่อดึงศักยภาพสูงสุดของลูกทีม',
    excerpt: 'หมดยุคการสั่งงานแบบ Micro-management หัวหน้างานยุคใหม่ต้องเป็น Facilitator และ Coach ที่ช่วยให้ทีมหาคำตอบและเติบโตด้วยตัวเองได้',
    date: '2024-01-08',
    thumbnail: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80',
  },
  {
    id: 'okrs-implementation-guide',
    type: 'blog',
    title: 'เจาะลึก OKRs: ตั้งเป้าหมายอย่างไรให้สอดคล้องและท้าทายทั้งองค์กร',
    excerpt: 'อธิบายแนวคิด OKRs ให้เข้าใจง่าย พร้อมข้อควรระวังและปัจจัยความสำเร็จ (Critical Success Factors) ในการนำ OKRs ไปใช้จริงในภาคธุรกิจ',
    date: '2023-12-25',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80',
  },
  {
    id: 'mental-health-in-workplace',
    type: 'blog',
    title: 'สุขภาวะทางจิตในที่ทำงาน (Mental Health) วาระเร่งด่วนขององค์กรยุคใหม่',
    excerpt: 'Burnout ทวีความรุนแรงขึ้น องค์กรและ HR จะออกแบบสวัสดิการและสภาพแวดล้อมอย่างไร เพื่อป้องกันและดูแลสุขภาพจิตของพนักงานด่านหน้า',
    date: '2023-12-11',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
  {
    id: 'design-thinking-for-hr',
    type: 'blog',
    title: 'Design Thinking for HR: ออกแบบประสบการณ์พนักงาน (EX) ให้โดนใจ',
    excerpt: 'ใช้กระบวนการคิดเชิงออกแบบ เพื่อเข้าไปนั่งในใจพนักงาน ตั้งแต่กระบวนการ Onboarding ไปจนถึง Offboarding ลดอัตราการลาออกและเพิ่มความผูกพัน',
    date: '2023-11-28',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80',
  },
  {
    id: 'data-driven-hr',
    type: 'blog',
    title: 'Data-Driven HR: เปลี่ยนสัญชาตญาณเป็นการตัดสินใจด้วยข้อมูล',
    excerpt: 'ก้าวข้ามการบริหารคนแบบเดิมด้วย HR Analytics เรียนรู้วิธีการจัดเก็บ วิเคราะห์ และนำข้อมูลมาใช้ในการพยากรณ์และป้องกันพนักงานลาออกล่วงหน้า',
    date: '2023-11-15',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80',
  },
  {
    id: '10-facilitation-tools',
    type: 'blog',
    title: '10 เครื่องมือ Facilitation ที่ช่วยทีมคิดและตัดสินใจเร็วขึ้น',
    excerpt: 'เครื่องมือ Facilitation ที่ดีเป็นเหมือนชุดกุญแจที่ Facilitator ใช้เปิดประตูสู่ Collective Intelligence ของทีม',
    date: '2026-02-17',
    thumbnail: 'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?auto=format&fit=crop&q=80',
  },
  {
    id: 'case-study-1day-team-transformation',
    type: 'blog',
    title: 'Case Study: องค์กรที่เปลี่ยนทีมได้ภายใน 1 วัน ด้วย Workshop',
    excerpt: 'Workshop 1 วันที่ออกแบบดีสามารถสร้างการเปลี่ยนแปลงที่ชัดเจนและวัดได้ในทีม ไม่ใช่แค่ความรู้สึกดีชั่วคราว',
    date: '2026-02-16',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'play-to-learn',
    type: 'blog',
    title: 'Play to Learn: ทำไมการเรียนรู้ที่สนุกถึงได้ผลมากกว่า',
    excerpt: 'การเล่นไม่ใช่ตรงข้ามกับการเรียนรู้ แต่คือเงื่อนไขที่ดีที่สุดสำหรับการเรียนรู้ที่ยั่งยืนในองค์กร',
    date: '2026-02-15',
    thumbnail: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&q=80',
  },
  {
    id: 'active-vs-passive-learning',
    type: 'blog',
    title: 'Active Learning vs Passive Learning: อะไรได้ผลจริงในองค์กร',
    excerpt: 'Passive Learning คือการรับข้อมูล ส่วน Active Learning คือการประมวลผล นำไปใช้ และสร้างความหมายด้วยตนเอง',
    date: '2026-02-14',
    thumbnail: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&q=80',
  },
  {
    id: 'what-is-facilitation',
    type: 'blog',
    title: 'Facilitation คืออะไร? ทำไมองค์กรชั้นนำถึงใช้',
    excerpt: 'Facilitation คือศิลปะและวิทยาศาสตร์ของการออกแบบและนำกระบวนการที่ช่วยให้กลุ่มคนคิด สื่อสาร และตัดสินใจได้อย่างมีประสิทธิภาพสูงสุด',
    date: '2026-02-13',
    thumbnail: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80',
  },
  {
    id: 'growth-mindset-vs-fixed-mindset',
    type: 'blog',
    title: 'Growth Mindset vs Fixed Mindset: อะไรทำให้คนเติบโตจริง',
    excerpt: 'Carol Dweck พิสูจน์แล้วว่า Mindset ไม่ใช่บุคลิกภาพที่ติดตัวมา แต่เป็นรูปแบบความเชื่อที่เปลี่ยนได้และส่งผลต่อความสำเร็จในระยะยาว',
    date: '2026-02-12',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'why-high-performers-burnout',
    type: 'blog',
    title: 'ทำไมคนเก่งถึง Burnout? และวิธีรีเซ็ตพลังใจ',
    excerpt: 'Burnout ไม่ได้เกิดกับคนขี้เกียจ แต่เกิดกับคนที่ทุ่มเทมากที่สุด สาเหตุหลักไม่ใช่การทำงานหนัก แต่คือการขาด Meaning และ Autonomy',
    date: '2026-02-11',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
  {
    id: 'cap-theory-self-discovery',
    type: 'blog',
    title: 'ค้นหาตัวตนด้วย CAP Theory: คุณกำลังใช้ศักยภาพเต็มหรือยัง',
    excerpt: 'CAP Theory มองศักยภาพของมนุษย์ผ่าน 3 มิติ: Consciousness, Awareness และ Presence เพื่อช่วยให้คุณรู้จักตัวเองในระดับที่ลึกขึ้น',
    date: '2026-02-10',
    thumbnail: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80',
  },
  {
    id: 'flow-state-at-work',
    type: 'blog',
    title: 'วิธีเข้าสู่ Flow State ในการทำงาน (ทำงานน้อยลง แต่ได้ผลมากขึ้น)',
    excerpt: 'Flow State ในการทำงานคือสภาวะที่ทำงานได้อย่างมีสมาธิสูงสุด มีพลังงาน และผลงานออกมาดีที่สุด โดยไม่รู้สึกว่ากำลังทำงานหนัก',
    date: '2026-02-09',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80',
  },
  {
    id: 'self-talk-change-life',
    type: 'blog',
    title: 'Self-Talk คืออะไร? เปลี่ยนคำพูดในใจ เปลี่ยนชีวิตได้จริงไหม',
    excerpt: 'Self-Talk คือเสียงในหัวที่พูดกับตัวเองตลอดวัน งานวิจัยพิสูจน์แล้วว่า Self-Talk เชิงบวกและเชิงลบส่งผลต่อสมรรถภาพและสุขภาพจิตอย่างมีนัยสำคัญ',
    date: '2026-02-08',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80',
  },
  {
    id: 'training-to-transformative-learning',
    type: 'blog',
    title: 'จาก Training สู่ Transformative Learning: HR ต้องเปลี่ยนอะไรบ้าง',
    excerpt: 'Transformative Learning เป็นการเรียนรู้ที่เปลี่ยนวิธีมองโลกและวิธีเป็นคน ไม่ใช่แค่การเพิ่มความรู้หรือทักษะ',
    date: '2026-02-07',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80',
  },
  {
    id: 'learning-journey-design',
    type: 'blog',
    title: 'Learning Journey คืออะไร? ออกแบบยังไงให้เกิดการเปลี่ยนแปลง',
    excerpt: 'Learning Journey คือเส้นทางการเรียนรู้ที่ออกแบบอย่างมีระบบเพื่อนำพาผู้เรียนจากจุดเริ่มต้นสู่เป้าหมายที่ต้องการ',
    date: '2026-02-06',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80',
  },
  {
    id: 'training-roi-measurement',
    type: 'blog',
    title: 'วัดผลการอบรมอย่างไรให้ผู้บริหาร "เห็น ROI จริง"',
    excerpt: 'ผู้บริหารไม่ได้ต้องการรู้ว่าพนักงาน "ชอบ" การอบรมหรือ "รู้" อะไรมาใหม่ แต่ต้องการเห็นว่าการอบรมสร้างผลลัพธ์ทางธุรกิจอย่างไร',
    date: '2026-02-05',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80',
  },
  {
    id: 'ai-facilitation-future',
    type: 'blog',
    title: 'AI + Facilitation: อนาคตของการพัฒนาคนในองค์กร',
    excerpt: 'AI เปลี่ยนการพัฒนาบุคลากรอย่างรุนแรง แต่ไม่ใช่การแทนที่ Facilitator แต่คือการ Augment ความสามารถของ Facilitator ให้ทรงพลังยิ่งขึ้น',
    date: '2026-02-04',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80',
  },
  {
    id: 'hr-as-learning-designer',
    type: 'blog',
    title: 'HR ยุคใหม่ต้องเป็น Learning Designer ไม่ใช่แค่ Trainer',
    excerpt: 'Trainer จัดอบรมและส่งเนื้อหา แต่ Learning Designer สร้างประสบการณ์ที่เปลี่ยนพฤติกรรมได้จริงและวัดผลได้',
    date: '2026-02-03',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80',
  },
  {
    id: 'feedback-culture-7-methods',
    type: 'blog',
    title: '7 วิธีสร้างวัฒนธรรม Feedback ที่ทีม "ไม่กลัว" แต่ "อยากฟัง"',
    excerpt: 'Feedback ที่ดีคือน้ำมันที่หล่อเลี้ยงการเติบโต แต่ Feedback ที่ผิดวิธีคือกรดที่กัดกร่อนความไว้วางใจในทีม',
    date: '2026-02-02',
    thumbnail: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80',
  },
  {
    id: 'psychological-safety-facilitation',
    type: 'blog',
    title: 'สร้าง Psychological Safety ในทีม ด้วย Facilitation',
    excerpt: 'Psychological Safety คือความรู้สึกปลอดภัยที่จะพูด ถาม ผิดพลาด และแสดงความคิดเห็นโดยไม่กลัวการถูกตัดสินหรือลงโทษ',
    date: '2026-02-01',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'team-talk-flow',
    type: 'blog',
    title: 'Team Talk Flow คืออะไร? ทำไมทีมเก่งยังสื่อสารพัง',
    excerpt: 'Team Talk Flow คือรูปแบบการสื่อสารในทีมที่ข้อมูลไหลสะดวก ไม่ติดขัด และทุกคนเข้าใจตรงกันโดยไม่ต้องอธิบายซ้ำ',
    date: '2026-01-31',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80',
  },
  {
    id: 'circle-dialogue-technique',
    type: 'blog',
    title: 'เทคนิค Circle Dialogue: เปลี่ยนความขัดแย้งเป็นความเข้าใจ',
    excerpt: 'Circle Dialogue คือกระบวนการพูดคุยในวงกลมที่ทุกคนมีสิทธิ์พูดเท่าเทียมกัน ไม่มีใครครอบงำการสนทนา',
    date: '2026-01-30',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
  {
    id: 'team-silo-connect-hearts',
    type: 'blog',
    title: 'ทีมทำงานแบบไซโล แก้อย่างไรให้ "เชื่อมใจ" ไม่ใช่แค่ "เชื่อมงาน"',
    excerpt: 'Silo Mentality เกิดขึ้นเมื่อแต่ละทีมหรือแผนกทำงานเพื่อตัวเองมากกว่าเพื่อองค์กร การแก้ต้องเริ่มจากการเชื่อมใจ ไม่ใช่แค่เชื่อมระบบ',
    date: '2026-01-29',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80',
  },
  {
    id: 'leader-as-facilitator',
    type: 'blog',
    title: 'ทำไมผู้นำที่ดี ต้องเป็น Facilitator ไม่ใช่ Instructor',
    excerpt: 'Instructor บอกคำตอบ แต่ Facilitator ช่วยให้คนหาคำตอบด้วยตัวเอง ผู้นำที่เป็น Facilitator สร้างทีมที่คิดเองได้และเติบโตอย่างยั่งยืน',
    date: '2026-01-28',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80',
  },
  {
    id: 'manager-to-leader-cap-theory',
    type: 'blog',
    title: 'จาก Manager สู่ Leader: เปลี่ยน Mindset ด้วย CAP Theory',
    excerpt: 'Manager บริหาร "งาน" แต่ Leader นำ "คน" สู่เป้าหมายที่ยิ่งใหญ่กว่า การเปลี่ยนจาก Manager เป็น Leader เริ่มจากการเปลี่ยน Mindset ด้วย CAP Theory',
    date: '2026-01-27',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80',
  },
  {
    id: 'leadership-speaking-trust',
    type: 'blog',
    title: 'Leadership Speaking: พูดอย่างไรให้ทีม "เชื่อ" ไม่ใช่แค่ "ฟัง"',
    excerpt: 'การพูดให้ทีมเชื่อไม่ใช่เรื่องของน้ำเสียงที่ดังหรือการใช้คำที่หรูหรา แต่คือการพูดด้วยความจริงใจและความชัดเจนที่สร้างความไว้วางใจ',
    date: '2026-01-26',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80',
  },
  {
    id: '5-leadership-skills-thai-orgs',
    type: 'blog',
    title: '5 ทักษะผู้นำที่องค์กรไทยขาด (และวิธีพัฒนาแบบยั่งยืน)',
    excerpt: 'องค์กรไทยมักส่งเสริมคนเก่งงานขึ้นเป็นหัวหน้าโดยไม่ได้พัฒนาทักษะการนำคน ทักษะที่ขาดนี้สร้างปัญหาใหญ่ในระยะยาว',
    date: '2026-01-25',
    thumbnail: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80',
  },
  {
    id: 'leader-deep-listening',
    type: 'blog',
    title: 'ผู้นำยุคใหม่ต้อง "ฟังให้ลึก" ไม่ใช่แค่ "สั่งให้เร็ว"',
    excerpt: 'ผู้นำที่ฟังเป็นสร้างทีมที่แข็งแกร่งกว่าผู้นำที่สั่งเก่ง Deep Listening ไม่ใช่การรอให้อีกฝ่ายพูดจบ แต่คือการรับรู้ทั้งคำพูดและสิ่งที่ไม่ได้พูด',
    date: '2026-01-24',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
];
