import { Resource } from '../types';

export const HRD_ARTICLES: Resource[] = [
  {
    id: 'hrd-future-skills-2025',
    type: 'blog',
    title: 'Future Skills 2025: ทักษะแห่งอนาคตที่ผู้นำองค์กรและ HRD ต้องรู้',
    excerpt: 'สำรวจทักษะสำคัญที่จำเป็นต่อการขับเคลื่อนองค์กรในโลกยุค BANI World พร้อมแนวทางการ Reskill และ Upskill พนักงานเพื่อให้พร้อมรับมือกับการเปลี่ยนแปลง',
    date: '2024-03-15',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80',
  },
  {
    id: 'building-growth-mindset-culture',
    type: 'blog',
    title: 'สร้างจิตสำนึกแห่งการเติบโต (Growth Mindset) ให้กลายเป็นวัฒนธรรมองค์กร',
    excerpt: 'Growth Mindset ไม่ใช่แค่ Buzzword แต่เป็นรากฐานสำคัญขององค์กรนวัตกรรม ครูเด่น มาสเตอร์ฟา เผยเคล็ดลับการปลูกฝัง Growth Mindset อย่างยั่งยืน',
    date: '2024-03-02',
    thumbnail: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80',
  },
  {
    id: 'effective-leadership-communication',
    type: 'blog',
    title: 'ศิลปะการสื่อสารสำหรับผู้นำ: เปลี่ยนคำพูดให้เป็นพลังขับเคลื่อนทีม',
    excerpt: 'ปัญหาความขัดแย้ง 80% เกิดจากการสื่อสารที่ไม่ชัดเจน เรียนรู้เทคนิคการสื่อสารแบบ Empathic Communication เพื่อซื้อใจลูกน้องและลดปัญหาในทีม',
    date: '2024-02-18',
    thumbnail: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80',
  },
  {
    id: 'employee-engagement-strategies',
    type: 'blog',
    title: '5 กลยุทธ์รักษาคนเก่ง (Talent Retention) ด้วย Employee Engagement',
    excerpt: 'การขึ้นเงินเดือนอาจไม่ใช่คำตอบเดียวเสมอไป ค้นพบปัจจัยทางจิตวิทยาและกระบวนการจัดการที่ทำให้คนเก่งอยากอยู่กับองค์กรของคุณไปนานๆ',
    date: '2024-02-05',
    thumbnail: 'https://images.unsplash.com/photo-1511376777868-611b54f68947?auto=format&fit=crop&q=80',
  },
  {
    id: 'agile-hr-transformation',
    type: 'blog',
    title: 'Agile HR: ปรับโฉมงานทรัพยากรบุคคลให้รวดเร็วและตอบโจทย์ธุรกิจ',
    excerpt: 'เมื่อวงจรธุรกิจสั้นลง HR ต้องเร็วกว่าเดิม เรียนรู้วิธีการนำหลักการ Agile มาใช้ในกระบวนการประเมินผล การพัฒนาบุคลากร และสรรหาบุคลากร',
    date: '2024-01-20',
    thumbnail: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80',
  },
  {
    id: 'coaching-skills-for-managers',
    type: 'blog',
    title: 'จาก Manager สู่ Coach: ทักษะการโค้ชเพื่อดึงศักยภาพสูงสุดของลูกทีม',
    excerpt: 'หมดยุคการสั่งงานแบบ Micro-management หัวหน้างานยุคใหม่ต้องเป็น Facilitator และ Coach ที่ช่วยให้ทีมหาคำตอบและเติบโตด้วยตัวเองได้',
    date: '2024-01-08',
    thumbnail: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&q=80',
  },
  {
    id: 'okrs-implementation-guide',
    type: 'blog',
    title: 'เจาะลึก OKRs: ตั้งเป้าหมายอย่างไรให้สอดคล้องและท้าทายทั้งองค์กร',
    excerpt: 'อธิบายแนวคิด OKRs ให้เข้าใจง่าย พร้อมข้อควรระวังและปัจจัยความสำเร็จ (Critical Success Factors) ในการนำ OKRs ไปใช้จริงในภาคธุรกิจ',
    date: '2023-12-25',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80',
  },
  {
    id: 'mental-health-in-workplace',
    type: 'blog',
    title: 'สุขภาวะทางจิตในที่ทำงาน (Mental Health) วาระเร่งด่วนขององค์กรยุคใหม่',
    excerpt: 'Burnout ทวีความรุนแรงขึ้น องค์กรและ HR จะออกแบบสวัสดิการและสภาพแวดล้อมอย่างไร เพื่อป้องกันและดูแลสุขภาพจิตของพนักงานด่านหน้า',
    date: '2023-12-11',
    thumbnail: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80',
  },
  {
    id: 'design-thinking-for-hr',
    type: 'blog',
    title: 'Design Thinking for HR: ออกแบบประสบการณ์พนักงาน (EX) ให้โดนใจ',
    excerpt: 'ใช้กระบวนการคิดเชิงออกแบบ เพื่อเข้าไปนั่งในใจพนักงาน ตั้งแต่กระบวนการ Onboarding ไปจนถึง Offboarding ลดอัตราการลาออกและเพิ่มความผูกพัน',
    date: '2023-11-28',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80',
  },
  {
    id: 'data-driven-hr',
    type: 'blog',
    title: 'Data-Driven HR: เปลี่ยนสัญชาตญาณเป็นการตัดสินใจด้วยข้อมูล',
    excerpt: 'ก้าวข้ามการบริหารคนแบบเดิมด้วย HR Analytics เรียนรู้วิธีการจัดเก็บ วิเคราะห์ และนำข้อมูลมาใช้ในการพยากรณ์และป้องกันพนักงานลาออกล่วงหน้า',
    date: '2023-11-15',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80',
  }
];
